BC_East = h5read('..\Larger_case_Dr_Chen\BC_hdf5_OK\BC_OK.h5','/BC_East/Data');
BC_West = h5read('..\Larger_case_Dr_Chen\BC_hdf5_OK\BC_OK.h5','/BC_West/Data');
BC_North = h5read('..\Larger_case_Dr_Chen\BC_hdf5_OK\BC_OK.h5','/BC_North/Data');
BC_South = h5read('..\Larger_case_Dr_Chen\BC_hdf5_OK\BC_OK.h5','/BC_South/Data');
t1 = 400;
t2 = 800;
t3 = 1200;
t4 = 1600;
t5 = 2000;
x1 = -798:4:798;
x2 = -448:4:448;
subplot(2,2,1);
%plot(1:120,BC_West_OK(:,t),'LineWidth',3);
title('West BC','fontsize',16);
hold all;
plot(x1,BC_West(t1,:),'LineWidth',3);
plot(x1,BC_West(t2,:),'LineWidth',3);
plot(x1,BC_West(t3,:),'LineWidth',3);
plot(x1,BC_West(t4,:),'LineWidth',3);
plot(x1,BC_West(t5,:),'LineWidth',3);
set(gca,'fontsize',16)
xlabel('Y','FontSize',18);
ylabel('h (m)','FontSize',18);
xlim([x1(1) x1(end)]);
box on;
%legend('Kriging','Test data');
subplot(2,2,2);
%plot(1:120,BC_East_OK(:,t),'LineWidth',3);
title('East BC','fontsize',16);
hold all;
plot(x1,BC_East(t1,:),'LineWidth',3);
plot(x1,BC_East(t2,:),'LineWidth',3);
plot(x1,BC_East(t3,:),'LineWidth',3);
plot(x1,BC_East(t4,:),'LineWidth',3);
plot(x1,BC_East(t5,:),'LineWidth',3);
%legend('Kriging','Test data');
legend('400 hours','800 hours','1200 hours','1600 hours','2000 hours');
set(gca,'fontsize',16)
xlabel('Y','FontSize',18);
ylabel('h (m)','FontSize',18);
xlim([x1(1) x1(end)]);
box on;
subplot(2,2,3);
%plot(1:120,BC_North_OK(:,t),'LineWidth',3);
title('North BC','fontsize',16);
hold all;
plot(x2,BC_North(t1,:),'LineWidth',3);
plot(x2,BC_North(t2,:),'LineWidth',3);
plot(x2,BC_North(t3,:),'LineWidth',3);
plot(x2,BC_North(t4,:),'LineWidth',3);
plot(x2,BC_North(t5,:),'LineWidth',3);
%legend('Kriging','Test data');
set(gca,'fontsize',16)
xlabel('X','FontSize',18);
ylabel('h (m)','FontSize',18);
box on;
xlim([x2(1) x2(end)]);
subplot(2,2,4);
%plot(1:120,BC_South_OK(:,t),'LineWidth',3);
title('South BC','fontsize',16);
hold all;
plot(x2,BC_South(t1,:),'LineWidth',3);
plot(x2,BC_South(t2,:),'LineWidth',3);
plot(x2,BC_South(t3,:),'LineWidth',3);
plot(x2,BC_South(t4,:),'LineWidth',3);
plot(x2,BC_South(t5,:),'LineWidth',3);
%legend('Kriging','Test data');
set(gca,'fontsize',16)
xlabel('X','FontSize',18);
ylabel('h (m)','FontSize',18);
xlim([x2(1) x2(end)]);
box on;